# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python38

# Despite the documentation, at least for dev_appserver, handlers aren't
# handled in order; instead the final /.* seems to catch things specified before
# it.
#
handlers:
  - url: /services/.*
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*\.(json|js|ico|png|html))$
    static_files: build/\1
    upload: build/.*\.(json|js|ico|png|html)$
    secure: always
    redirect_http_response_code: 301
  - url: /static
    static_dir: build/static/
    secure: always
    redirect_http_response_code: 301
    expiration: 365d
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

env_variables:
  # Firebase
  FIREBASE_PROJECT_ID: 'bikebuds-app'
