runtime: python27
api_version: 1
threadsafe: true
service: backend

libraries:
- name: ssl
  version: latest

handlers:
- url: /.*
  script: main.app

env_variables:
  FIREBASE_PROJECT_ID: 'bikebuds-app'
