# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import unittest

from shared.datastore.subscription_event import SubscriptionEvent


class SubscriptionEventTest(unittest.TestCase):
    def test_hash_name(self):
        args = ['AAA', 'BBB', 'CCC']
        hash_name = SubscriptionEvent.hash_name(*args)
        # Hash guarenteed, generated by D6. :)
        self.assertEqual('2236edf1239b64ae48b309fb0bf15cdf6ddbf921', hash_name)

        reversed_hash_name = SubscriptionEvent.hash_name(*reversed(args))
        # Hash guarenteed, generated by D6. :)
        self.assertEqual('2ef291e5b3091198086ee74855e348436a6f4b36', reversed_hash_name)
